ponycheckup/check/urls.py
from django.conf.urls import *

from views import EnterUrlView, ResultView, ResultAjaxView

urlpatterns = patterns('',
    url(r'^$', EnterUrlView.as_view(), name="enterurl"),
    url(r'^result/$', ResultView.as_view(), name="result"),
    url(r'^result_ajax/$', ResultAjaxView.as_view(), name="result_ajax"),
)

ponycheckup/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ponycheckup.views.home', name='home'),
    url(r'^', include('ponycheckup.check.urls', namespace="check")),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

ponycheckup/check/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel


class Check(TimeStampedModel):
    url                     = models.URLField()

    no_of_recommendations   = models.IntegerField(default=0)

    runs_debug              = models.BooleanField()

    supports_https          = models.BooleanField()
    heartbleed_vuln         = models.BooleanField()
    hsts_header_found       = models.BooleanField()
    xframe_header_found     = models.BooleanField()

    admin_found             = models.BooleanField()
    admin_forces_https      = models.NullBooleanField()

    login_found             = models.BooleanField()
    login_forces_https      = models.NullBooleanField()

    allows_trace            = models.BooleanField()

    csrf_cookie_found       = models.BooleanField()
    session_cookie_found    = models.BooleanField()
    session_cookie_secure   = models.NullBooleanField()
    session_cookie_httponly = models.NullBooleanField()

    def update_recommendation_count(self):
        self.no_of_recommendations = 0

        if self.runs_debug:                                  self.no_of_recommendations += 1
        if not self.supports_https:                          self.no_of_recommendations += 1
        if self.heartbleed_vuln:                             self.no_of_recommendations += 1
        if not self.hsts_header_found:                       self.no_of_recommendations += 1
        if not self.xframe_header_found:                     self.no_of_recommendations += 1
        if self.admin_found and not self.admin_forces_https: self.no_of_recommendations += 1
        if self.login_found and not self.login_forces_https: self.no_of_recommendations += 1
        if self.allows_trace:                                self.no_of_recommendations += 1
        #if not self.csrf_cookie_found:                       self.no_of_recommendations += 1
        if self.session_cookie_found and not self.session_cookie_secure:   self.no_of_recommendations += 1
        if self.session_cookie_found and not self.session_cookie_httponly: self.no_of_recommendations += 1

    @property
    def secure_percentage(self):
        # worst is 10, best is 0
        return int(100-round(10*self.no_of_recommendations))

    @property
    def proven_django(self):
        return self.runs_debug or self.csrf_cookie_found or self.session_cookie_found or self.admin_found

ponycheckup/check/views.py
# Create your views here.
import datetime
import time
from django.views.generic.base import TemplateView
import re
from .models import Check
from .checker import SecurityChecker

MINIMAL_CHECK_TIME = 2.5


class EnterUrlView(TemplateView):
    template_name = 'check/enter_url.html'


class ResultView(TemplateView):
    template_name = 'check/result.html'


class ResultAjaxView(TemplateView):
    template_name = 'check/result_ajax.html'

    def dispatch(self, request, *args, **kwargs):
        start_time = time.time()
        response = super(ResultAjaxView, self).dispatch(request, *args, **kwargs)
        wait_time = start_time + MINIMAL_CHECK_TIME - time.time()
        if wait_time > 0:
            time.sleep(wait_time)
        return response

    def get_context_data(self, **kwargs):
        context = super(ResultAjaxView, self).get_context_data(**kwargs)

        try:
            url = self.request.GET['url']
        except KeyError:
            context['could_not_load'] = True
            return context

        url = self.sanitize_url(url)
        if not url:
            context['could_not_load'] = True
            return context

        checker = SecurityChecker()
        force_refresh = self.request.GET.get('force_refresh', None)

        existing_objects = Check.objects.filter(url=url)
        if not force_refresh and len(existing_objects) and datetime.datetime.now()-existing_objects[0].created < datetime.timedelta(minutes=5):
            check_result = existing_objects[0]
            context['reused_existing_object'] = True
        else:
            check_result = checker.run_check(url)

        if check_result and isinstance(check_result, Check):
            context['check_record'] = check_result
            percentage = check_result.secure_percentage

            if percentage >= 85:
                context['score_good'] = True
            elif percentage >= 50:
                context['score_warning'] = True
            else:
                context['score_bad'] = True

        else:
            context['could_not_load'] = True
            context['error'] = check_result
        return context

    def sanitize_url(self, url):
        url = re.sub("http.?://", '', url)
        url = url.split("/")[0]
        if not re.match("^[A-z0-9\.-]+$", url):
            return False

        return "http://"+url

ponycheckup/check/templates/check/enter_url.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="hero-unit">
    <img src="{{ STATIC_URL}}logo.png" style="float: right;">
    <h1>Give your Django pony a security checkup.</h1>
    <br />
    <p style="margin-bottom: 35px">Are you running a Django website? Security can be tricky business, and it's easy to forget something.</p>
    <form action="{% url 'check:result' %}" method="get" class="form-inline" >
        <label style="margin-top: 15px; height: 5px; font-size: 30px;">Enter your domain name:</label>
        <input style="margin-top: 15px; clear:both; height: 40px; font-size: 30px; width: 500px" placeholder="e.g. djangoproject.com" type="text" name="url" />
        <input style="margin-top: 15px; height: 50px; font-size: 30px;" type="submit" class="btn btn-primary" value="Check up"/>
    </form>
    <p align="right" style="margin-right: 2em"><em>
        Results are only reliable for Django websites.
    </em></p>
</div>


<div class="row">
    <div class="span4">
        <h2>What is this?</h2>
        <p class="lead"><em>Sasha's Pony Checkup</em> is a basic automated security checkup for <a href="http://djangoproject.com">Django</a>
            websites. There are several security practices that can easily be probed from the outside, and this is what
            Sasha's Pony Checkup looks for.</p>
        <p>Knowing what's wrong is only the first step:
            Sasha's Pony Checkup helps by explaining not just the risks, but also gives hints on how to best fix an issue.</p>
        <p><em>This is not a replacement for a full security audit.</em> But it is a
            simple and fast way of seeing several basic pressing issues. Do note that there are many vulnerabilities which
            can not be detected in this way, like SQL or XSS injection.</p>
    </div>
    <div class="span4">
        <h2>Why did you build this?</h2>
        <p class="lead">To help <a href="http://www.mxsasha.eu/blog/2013/12/15/appeal-for-security-for-the-ordinary-developer/">the ordinary developer</a>
            to take a step with securing their Django projects.
            In June 2012, I spoke at <a href="http://2012.djangocon.eu">Djangocon Europe</a>
            about Building secure Django websites
            which met with great response. I was inspired to build this tool by Jessica McKellar's
            <a href="http://klewel.com/conferences/djangocon-2012/index.php?talkID=35">keynote</a>, in which
            she explained how hard all this can be for people new to Django.</p>
        <p>In addition, many experienced Django developers approached me after my talk to admit that they had made
            some of the errors I mentioned. Someone even made a serious error on stage the next day. This, combined with the fact
            that quite a few things can easily be checked remotely with a few HTTP requests, inspired me to build this.</p>
    </div>
    <div class="span4">
        <h2>Who built this?</h2>
        <p class="lead">I'm <a href="http://twitter.com/mxsash">Sasha Romijn</a>, mostly a developer and mainly focusing on Python/Django.
            I live in Amsterdam, The Netherlands. I’m passionate about building inclusive communities, technology and conferences, where everyone
            can feel welcome, valued and at home. I’m also particularly interested in issues around well-being and ethics in tech.</p>
    </div>
</div>

{% endblock %}

ponycheckup/check/templates/check/result.html
{% extends "base.html" %}

{% block content %}

    <div id="report" xmlns="http://www.w3.org/1999/html">
        <h1>Working on your report...</h1>
        <br />
        <div class="progress progress-striped active">
            <div class="bar" style="width: 0%;"></div>
        </div>

        <div class="timeout clearfix" style="display: none">
            <hr />
            <a style="float: left; margin-right: 20px" href="http://xkcd.com/612/" target="_blank"><img src="http://imgs.xkcd.com/comics/estimation.png" /></a>
            <h2>Oh dear. This is quite embarassing.</h2>
            <p class="lead">It seems our progress bar filled up before we could finish your report.
            Well, estimation can be quite hard. We'll try to get your results to you as soon as possible.
            </p>
        </div>

    </div>
    <script type="text/javascript">
        $.get("{% url 'check:result_ajax' %}?{{ request.META.QUERY_STRING }}", function(data) {
            $('#report').html(data);
        }).fail(function() {
            $('#report').html('<div class="alert alert-error"><h4 class="alert-heading">Server error</h4>Something appears to have gone wrong in the generation of your report. We\'ve been automatically notified, and aim to resolve this as soon as possible. Apologies for the inconvenience.');
        });

        var progress = 0;
        increaseProgress(null);
        function increaseProgress(event) {
            progress += 3;

            if (progress <= 100) {
                $('.bar').css('width', progress+'%');
            }
            if (progress <= 130) {
                setTimeout(increaseProgress, 400);
            } else {
                $('.timeout').slideDown();
            }
        }
    </script>
{% endblock %}

ponycheckup/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Sasha's pony checkup</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Give your Django website an automatic security checkup. If you have security issues, get useful tips on how to improve.">
<meta name="d1dda1db90403cd6f18ccd4d76d832462411f034" content="546821ac1000f87012cfbf69d55e196e2629e324" />

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.css" rel="stylesheet">
    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <script src="{{ STATIC_URL }}js/jquery.min.js"></script>


</head>

<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="/">Sasha's Pony Checkup</a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li class="active"><a href="/">Home</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>

<div class="container">

    {% block content %}{% endblock %}

    <hr>

    <footer>
        <p>Built by <a href="http://twitter.com/mxsash/">Sasha Romijn</a>. Source on <a href="https://github.com/mxsasha/ponycheckup">GitHub</a>.
            Reports generated by this tool have a margin of error and are not meant to replace serious security audits.
            Note that this report provides tips on how to improve
            security, and do not indicate whether or not a web app has or has not been compromised.
            Logo based on <a href="http://fureox.deviantart.com/art/Armored-Knight-Pony-345605280">
                Armored Knight Pony by Fureox.
            </a>
        </p>
    </footer>
</div> <!-- /container -->
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap-min.js"></script>
</body>
</html>